InternLM/HuixiangDou

- .github/scripts/daily_smoke.py
- huixiangdou/service/sg_search.py
* fix source graph prompt
* fix CI config path
> fix(CI): update config.ini path

- huixiangdou/service/llm_server_hybrid.py
- requirements.txt
> feat(huixiangdou): compatible with qwen1.5

- docs/add_lark_group_zh.md
update md according to latest practise
> docs(lark_group): add FAQ

- web/front-end/src/app.tsx
- web/front-end/src/components/notification/emoji-wrapper.tsx
- web/front-end/src/components/notification/notification.module.less
- web/front-end/src/components/notification/notification.tsx
- web/front-end/src/components/notification/use-notification.tsx
- web/front-end/src/components/upload/upload.module.less
- web/front-end/src/pages/bean-detail/components/chat/chat.module.less
- web/front-end/src/pages/home/home.module.less
- add typing animation
- add notification
> web-fe: add typing animation

- web/front-end/src/pages/bean-detail/components/chat/chat.module.less
- web/front-end/src/pages/bean-detail/components/chat/chat.tsx
- modify styles
- scroll to bottom automatically
> web-fe: update chat feature

- huixiangdou/service/llm_server_hybrid.py
> fix(llm_server_hybrid.py): bad role

- README.md
- README_zh.md
- config.ini
- docs/add_wechat_accessibility_zh.md
- huixiangdou/service/llm_server_hybrid.py
* support xi-api
* update docs
> feat(service/llm_server_hybrid.py): support xi-api

- web/service/cache.py
2. print environment parameter when start
> 1. bug fix

- web/proxy/config-template.ini
- web/proxy/config.py
- web/proxy/llm_client.py
- web/proxy/llm_server_hybrid.py
- web/proxy/main.py
- web/proxy/worker.py
* update LLM
* redis initialization use env
* redis add keepalive
> feat(web/proxy): suppor internlm-123B

- android/.idea/misc.xml
- android/demo/src/main/java/com/carlos/grabredenvelope/demo/MainActivity.kt
- android/demo/src/main/java/com/carlos/grabredenvelope/demo/SendEmojiService.kt
- android/demo/src/main/java/com/carlos/grabredenvelope/demo/SharedPreferenceHelper.kt
- android/demo/src/main/res/layout/activity_main.xml
- android/demo/src/main/res/values/strings.xml
* add `Switch` for debugging
* fix fetch user input
* support web version callback url
> feat(android): new fetch user input

- web/proxy/feature_store.py
- web/proxy/llm_server_hybrid.py
* single file text length cannot exceed 400k
> feat(web/proxy): add max file length

- .pre-commit-config.yaml
- huixiangdou/service/feature_store.py
- huixiangdou/service/file_operation.py
- huixiangdou/service/llm_server_hybrid.py
- huixiangdou/service/retriever.py
- huixiangdou/version.py
- requirements.txt
- tests/test_benepar.py
- tests/test_optimum_st.py
* fix filename and conflict too long on ubuntu
* optimize pdf parsing table
* speedup pdf parsing with `multiprocess`  and `sha256`,   build `feature_store` would be faster
> feat(huixiangdou): pdf support parse table

- README.md
- README_zh.md
- config.ini
- docs/add_wechat_accessibility_zh.md
- tests/test_post_android.py
> docs(README.md): add bilibi video and format

- huixiangdou/service/retriever.py
Reverts InternLM/HuixiangDou#151
> Revert "de-serialization relies loading a pickle file need allow_dangerous_deserialization=True"

- web/front-end/src/locales/zh-CN/home.ts
- web/proxy/main.py
> feat(web/proxy): typo

- README.md
- README_zh.md
- huixiangdou/service/feature_store.py
- huixiangdou/service/file_operation.py
- tests/test_step1_llm.py
* support ppt format
* add `test_step1_llm.py`
> feat(huixiangdou): support ppt and test step1 LLM

- README.md
- README_zh.md
- huixiangdou/service/feature_store.py
* improve zh_cn text splitter when input text has redundant space, copy from langchain-chatchat
> improvement(service/feature_store.py): format bad text

- huixiangdou/service/retriever.py
> fix(retriever.py): enumerate dict error

- README.md
- README_zh.md
- huixiangdou/service/feature_store.py
- huixiangdou/service/file_operation.py
* support html format
* test on [https://en.cppreference.com/w/File:html_book_20190607.zip](https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxcheckurl?requrl=https%3A%2F%2Fen.cppreference.com%2Fw%2FFile%3Ahtml_book_20190607.zip&skey=%40crypt_c8bdef75_ce6cd8ef91c1738c33079aa7dcbbf3ed&deviceid=e033205186839079&pass_ticket=undefined&opcode=2&scene=1&username=@71fc4b427b12785ae7c93f0c53624d57b896366d08182c131ca4a3bcf1baed2b)
> feat(file_operation.py): support html format

- tests/test_query_gradio.py
* upgrade gradio service
usage:
```python3
optional arguments:
-h, --help            show this help message and exit
--work_dir WORK_DIR   Working directory.
--config_path CONFIG_PATH
Worker configuration path. Default value is config.ini
--standalone          Auto deploy required Hybrid LLM Service.
```
Result shotcut:
> feat(tests): upgrade gradio server

- .github/scripts/config-ci.ini
- huixiangdou/main.py
- huixiangdou/service/__init__.py
- huixiangdou/service/config.py
- huixiangdou/service/feature_store.py
- huixiangdou/service/file_operation.py
- huixiangdou/service/helper.py
- huixiangdou/service/llm_client.py
- huixiangdou/service/llm_server_hybrid.py
- huixiangdou/service/sg_search.py
- huixiangdou/service/worker.py
- requirements.txt
- setup.py
- tests/test_query_gradio.py
* support puyu API
* refactor `remote` parameter, use `backend`
if backend == 'remote', use remote LLM in `config.ini`; elif backend =='local' use local LLM in config.
Thus we could specify multiple remote LLM in pipeline.
> feat(service): support puyu, refactor llm backend

- web/README.md
- web/proxy/main.py
bugfix, missing `config-template.ini`
> fix(web): use config.ini instead of config-template.ini

- android/.idea/misc.xml
- android/demo/src/main/java/com/carlos/grabredenvelope/demo/SendEmojiService.kt
- android/demo/src/main/res/values/strings.xml
- docs/add_wechat_accessibility_zh.md
- web/front-end/src/components/upload/upload.tsx
- web/front-end/src/locales/en-US/bean-detail.ts
- web/front-end/src/locales/zh-CN/bean-detail.ts
* fix the acquisition of the latest messages on WeChat
* fix debug mode and typo in android
* web support html and pptx
> fix(android): support single chat and bugfix message acquisition

- README.md
- README_zh.md
No module named 'faiss.swigfaiss_avx2'问题修复
> No module named 'faiss.swigfaiss_avx2'问题修复 Update README_zh.md

- web/README.md
> docs(web): fix installation

- README.md
- README_zh.md
- config-experience.ini
- docs/architecture_en.md
- docs/architecture_zh.md
- huixiangdou/service/file_operation.py
- huixiangdou/service/llm_server_hybrid.py
- huixiangdou/service/retriever.py
- web/proxy/main.py
- web/proxy/worker.py
Reverts InternLM/HuixiangDou#216
> Revert "feat(web/proxy): remove security"

- web/model/huixiangdou.py
- web/service/agent.py
- web/service/cache.py
- web/service/chat.py
huixiangdou/web/service/cache.py
huixiangdou/web/model/huixiangdou.py
huixiangdou/web/service/chat.py
huixiangdou/web/service/agent.py
> improvement(web/service): use List instead of list

- android/demo/src/main/java/com/carlos/grabredenvelope/demo/MainActivity.kt
* android
load  saved URL and `Toast`
> fix(android): auto load URL

- README.md
- README_zh.md
- huixiangdou/rag.py
- huixiangdou/service/__init__.py
- huixiangdou/service/file_operation.py
- huixiangdou/service/helper.py
- huixiangdou/service/llm_client.py
- huixiangdou/service/llm_server_hybrid.py
- huixiangdou/service/worker.py
- tests/test_kimi_passkey.py
- unittest/test_llm_client.py
- unittest/test_llm_server_hybrid.py
- web/README.md
- web/main.py
- web/proxy/web_worker.py
- web/service/agent.py
- web/service/cache.py
- web/service/chat.py
* check llm loading and usage mismatch in `llm_server_hybrid.py`
* format the code
> improvement(llm_server_hybrid.py): check llm loading and usage mismatch

- huixiangdou/__init__.py
- huixiangdou/version.py
- requirements.txt
- setup.py
* fix textract installation error
> fix(requirements.txt): use forked textract

- tests/tool_dump_redis_query.py
- web/proxy/main.py
> feat(tests): add dump all redis query

- tests/test_openai.py
- web/tools/reconstruct_filter_annotate.py
- web/tools/reconstruct_wechat_group.py
> improvement(web/tools): optimize metric tool

- web/tools/convert_to_alpaca.py
* convert annotated data to alpaca format
> feat(web/tools): add alpaca conversion

- android/demo/src/main/java/com/carlos/grabredenvelope/demo/MainActivity.kt
- android/demo/src/main/java/com/carlos/grabredenvelope/demo/SendEmojiService.kt
- android/demo/src/main/java/com/carlos/grabredenvelope/demo/WechatConstants.kt
- android/demo/src/main/res/values/strings.xml
- docs/add_wechat_accessibility_zh.md
* Locate sender message by header `ImageView`
* Support WeChat 8.0.48 + 8.0.49
* Add url input check
New apk already released to https://github.com/InternLM/HuixiangDou/releases/tag/v0.1.0rc1
> improvement(android): optimize message gathering

- huixiangdou/frontend/wechat.py
> refactor(huixiangdou): update wechat.py

- README.md
- README_zh.md
- huixiangdou/service/__init__.py
- huixiangdou/service/helper.py
- huixiangdou/service/llm_server_hybrid.py
- huixiangdou/service/web_search.py
- unittest/test_llm_server_local.py
- unittest/test_web_search.py
* support qwen2
* fix internlm2 scoring
* fix web search crash within async context
> feat(huixiangdou): add internlm2 ci test

- README.md
- README_zh.md
- docs/add_wechat_commercial_zh.md
- huixiangdou/frontend/lark_group.py
- huixiangdou/frontend/wechat.py
- huixiangdou/service/__init__.py
- huixiangdou/service/helper.py
- huixiangdou/service/llm_server_hybrid.py
- huixiangdou/service/primitive.py
- huixiangdou/service/sg_search.py
- huixiangdou/service/web_search.py
- huixiangdou/service/worker.py
- requirements.txt
- tests/test_kimi.py
- tests/test_pyppeteer.py
- unittest/test_llm_server_hybrid.py
- unittest/test_llm_server_local.py
- unittest/test_web_search.py
* support download pdf and docx file when parsing web search result.
> feat(web_search.py): support file download and parsing

- .gitignore
- evaluation/README_zh.md
- evaluation/rejection/build_fs_and_filter.py
- evaluation/rerank/step0_clean_queries.py
- evaluation/rerank/step1_create_candidates.py
- huixiangdou/service/feature_store.py
- huixiangdou/service/file_operation.py
- huixiangdou/service/helper.py
- huixiangdou/service/retriever.py
- tests/test_bge_reranker.py
- tests/test_m3.py
- tests/test_milvus_hybrid_retrieval.py
1. add testdata for rerank evaluation
2. bugfix
> feat(evaluation/rerank): add testdata

- .gitignore
- huixiangdou/frontend/wechat.py
- huixiangdou/service/worker.py
- tests/test_clear_kimi_files.py
Two funny features:
*  **Learning through the chat group.** If you receive a revert command, use a higher threshold. AKA "群友学习法"
* Remove outdated (> 1 hour) chat history
> feat(wechat.py): learning through the chat group

- web/front-end/scripts/proxy.ts
- web/front-end/src/components/upload/delete-btn.tsx
- web/front-end/src/components/upload/upload.module.less
- web/front-end/src/components/upload/upload.tsx
- web/front-end/src/locales/en-US/components.ts
- web/front-end/src/locales/zh-CN/components.ts
- web/front-end/src/pages/bean-detail/bean-detail.tsx
- web/front-end/src/pages/bean-detail/components/import-docs/import-docs.tsx
- web/front-end/src/services/home.ts
- delete docs, and support deleting multiple files at the same time
- front-end
> feat(web/frontend): add delete docs

- huixiangdou/service/llm_server_hybrid.py
> fix(service): add process spawn

- huixiangdou/server.py
correct the main_args to args
[issue id: 364](https://github.com/InternLM/HuixiangDou/issues/364)
> fix undefined main_args in server.py

- huixiangdou/frontend/wechat.py
`wechat.py` support message forwarding
- normal text message
- reference message
- image
- url
> feat(wechat.py): optimize wechat forward

- huixiangdou/frontend/wechat.py
> fix(wechat.py): filter msg by unique id
